[project]
name = "src"
version = "0.1.0"
description = "Project to track grand exchange prices and other relevant informations"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]